[package]
name = "test-contract"
version = "0.1.0"
edition = "2018"

[features]
test-bpf = []
no-entrypoint = []

[dependencies]
pyth-sdk-solana = { path = "../" }
solana-program = "1.8.1"
bytemuck = "1.7.2"
borsh = "0.9"
borsh-derive = "0.9.0"

[dev-dependencies]
solana-program-test = "1.8.1"
solana-client = "1.8.1"
solana-sdk = "1.8.1"
